name: AIHC
channels:
  - conda-forge
  - defaults
platforms:
  - osx-arm64
dependencies:
  - python=3.11.10
  - pip=24.2
  - notebook=7.2.2
  - ipywidgets=8.1.5
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - pytorch=2.4.1
  - pybind11=2.13.6
  - gensim=4.3.2
  - scikit-learn=1.5.2
  - transformers=4.45.1
  - nltk=3.9.1
  - scipy=1.10.1
  - pip:
      - nmslib @ git+https://github.com/nmslib/nmslib.git#subdirectory=python_bindings
      - spacy[apple]==3.7.5
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl
      - scispacy==0.5.4
      - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz